# Generated by Django 3.0.8 on 2020-07-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.TextField(blank=True),
        ),
    ]
