# Generated by Django 3.0.8 on 2020-08-14 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20200811_2049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollowing',
            options={},
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='created',
        ),
    ]
