# Generated by Django 3.0.8 on 2020-08-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20200814_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollowing',
            options={},
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='created',
        ),
    ]
