# Generated by Django 3.0.8 on 2020-08-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20200816_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollowing',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together=set(),
        ),
    ]
