# Generated by Django 3.0.8 on 2020-08-16 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_auto_20200816_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowing',
            name='created',
        ),
    ]
