# Generated by Django 3.0.8 on 2020-08-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_auto_20200816_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfollowing',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='userfollowing',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='created',
        ),
    ]
